In [ ]:
import numpy

## Essential NumPy Methods for AI/ML

NumPy is a fundamental library for numerical computing in Python, especially crucial for AI and Machine Learning due to its efficient array operations. Below are some essential methods and concepts.

### 1. Array Creation

#### `np.array()`: Creating arrays from Python lists or tuples.

In [ ]:
import numpy as np

# Exercise 1.1: Create a 1D array from a list
list_1d = [1, 2, 3, 4, 5]
array_1d = np.array(list_1d)
print(f"1D Array: {array_1d}\nShape: {array_1d.shape}")

# Exercise 1.2: Create a 2D array from a list of lists
list_2d = [[1, 2, 3], [4, 5, 6]]
array_2d = np.array(list_2d)
print(f"\n2D Array:\n{array_2d}\nShape: {array_2d.shape}")


1D Array: [1 2 3 4 5]
Shape: (5,)

2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


#### `np.zeros()`: Creates an array filled with zeros.
#### `np.ones()`: Creates an array filled with ones.
#### `np.full()`: Creates an array filled with a specified value.
#### `np.empty()`: Creates an array without initializing its entries (can contain garbage values).
#### `np.arange()`: Creates an array with a range of values.
#### `np.linspace()`: Creates an array with evenly spaced numbers over a specified interval.

In [ ]:
# Exercise 1.3: Create arrays using various initialization methods

# 3x3 array of zeros
zeros_array = np.zeros((3, 3))
print(f"\nArray of Zeros (3x3):\n{zeros_array}")

# 2x4 array of ones
ones_array = np.ones((2, 4))
print(f"\nArray of Ones (2x4):\n{ones_array}")

# 2x2 array filled with 7
full_array = np.full((2, 2), 7)
print(f"\nArray filled with 7 (2x2):\n{full_array}")

# 1D array from 0 to 9
range_array = np.arange(10)
print(f"\nArray with range (0-9): {range_array}")

# 1D array of 5 evenly spaced numbers between 0 and 1
linspace_array = np.linspace(0, 1, 5)
print(f"\nArray with linspace (5 points between 0 and 1): {linspace_array}")



Array of Zeros (3x3):
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Array of Ones (2x4):
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Array filled with 7 (2x2):
[[7 7]
 [7 7]]

Array with range (0-9): [0 1 2 3 4 5 6 7 8 9]

Array with linspace (5 points between 0 and 1): [0.   0.25 0.5  0.75 1.  ]


### 2. Array Manipulation

#### `array.reshape()`: Gives a new shape to an array without changing its data.
#### `array.flatten()` or `array.ravel()`: Flattens a multi-dimensional array into a 1D array.
#### `array.transpose()` or `array.T`: Permutes the dimensions of an array.

In [ ]:
# Exercise 2.1: Reshape an array
original_array = np.arange(12)
print(f"Original array: {original_array}\nShape: {original_array.shape}")

reshaped_array = original_array.reshape(3, 4)
print(f"\nReshaped to 3x4:\n{reshaped_array}\nShape: {reshaped_array.shape}")

# Exercise 2.2: Flatten an array
flattened_array = reshaped_array.flatten()
print(f"\nFlattened array: {flattened_array}\nShape: {flattened_array.shape}")

# Exercise 2.3: Transpose an array
transposed_array = reshaped_array.T
print(f"\nTransposed array (4x3):\n{transposed_array}\nShape: {transposed_array.shape}")


Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape: (12,)

Reshaped to 3x4:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape: (3, 4)

Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape: (12,)

Transposed array (4x3):
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Shape: (4, 3)


### 3. Basic Operations (Element-wise)

NumPy arrays support element-wise operations for addition, subtraction, multiplication, division, and more. This is much faster than doing these operations with Python lists using loops.

In [ ]:
# Exercise 3.1: Element-wise addition, multiplication, and comparison
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(f"Array a: {a}")
print(f"Array b: {b}")

# Addition
print(f"\nAddition (a + b): {a + b}")

# Multiplication
print(f"Multiplication (a * b): {a * b}")

# Scalar multiplication
print(f"Scalar Multiplication (a * 2): {a * 2}")

# Comparison
print(f"Comparison (a > 2): {a > 2}")


Array a: [1 2 3]
Array b: [4 5 6]

Addition (a + b): [5 7 9]
Multiplication (a * b): [ 4 10 18]
Scalar Multiplication (a * 2): [2 4 6]
Comparison (a > 2): [False False  True]


### 4. Array Indexing and Slicing

NumPy's powerful indexing and slicing capabilities allow for efficient access and modification of array elements.

In [ ]:
# Exercise 4.1: Accessing elements in 1D and 2D arrays

array_1d = np.array([10, 20, 30, 40, 50])
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(f"1D Array: {array_1d}")
print(f"2D Array:\n{array_2d}")

# Access the third element of array_1d (index 2)
print(f"\nThird element of 1D array: {array_1d[2]}")

# Access the element at row 1, column 2 of array_2d (value 6)
print(f"Element at (row 1, col 2) in 2D array: {array_2d[1, 2]}")

# Exercise 4.2: Slicing 1D and 2D arrays

# Get elements from index 1 to 3 (exclusive of 4) in array_1d
print(f"\nSliced 1D array (index 1 to 3): {array_1d[1:4]}")

# Get the first two rows of array_2d
print(f"First two rows of 2D array:\n{array_2d[:2]}")

# Get all rows, but only the second column
print(f"Second column of 2D array:\n{array_2d[:, 1]}")

# Get the sub-array consisting of the first two rows and the last two columns
print(f"Sub-array (first two rows, last two columns):\n{array_2d[:2, 1:]}")

# Exercise 4.3: Boolean indexing (useful for filtering data)

# Select elements from array_1d that are greater than 30
filtered_array = array_1d[array_1d > 30]
print(f"\nElements > 30 in 1D array: {filtered_array}")

# Select rows from array_2d where the first column is greater than 3
filtered_rows = array_2d[array_2d[:, 0] > 3]
print(f"Rows where first column > 3 in 2D array:\n{filtered_rows}")


1D Array: [10 20 30 40 50]
2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Third element of 1D array: 30
Element at (row 1, col 2) in 2D array: 6

Sliced 1D array (index 1 to 3): [20 30 40]
First two rows of 2D array:
[[1 2 3]
 [4 5 6]]
Second column of 2D array:
[2 5 8]
Sub-array (first two rows, last two columns):
[[2 3]
 [5 6]]

Elements > 30 in 1D array: [40 50]
Rows where first column > 3 in 2D array:
[[4 5 6]
 [7 8 9]]


### 5. Aggregation Functions

NumPy provides highly optimized functions for performing aggregations like sum, mean, standard deviation, min, max, etc., often much faster than Python's built-in functions, especially on large arrays. These can be performed over the entire array or along specific axes (rows or columns).

In [ ]:
# Exercise 5.1: Basic aggregations on a 1D array
data_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(f"1D Data: {data_1d}")

print(f"\nSum: {data_1d.sum()}")
print(f"Mean: {data_1d.mean():.2f}")
print(f"Min: {data_1d.min()}")
print(f"Max: {data_1d.max()}")
print(f"Standard Deviation: {data_1d.std():.2f}")


1D Data: [ 1  2  3  4  5  6  7  8  9 10]

Sum: 55
Mean: 5.50
Min: 1
Max: 10
Standard Deviation: 2.87


In [ ]:
# Exercise 5.2: Aggregations along axes on a 2D array
data_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"2D Data:\n{data_2d}")

# Sum of all elements
print(f"\nTotal Sum: {data_2d.sum()}")

# Sum along columns (axis=0) - sum of elements in each column
print(f"Sum along columns (axis=0): {data_2d.sum(axis=0)}")

# Sum along rows (axis=1) - sum of elements in each row
print(f"Sum along rows (axis=1): {data_2d.sum(axis=1)}")

# Mean along columns (axis=0)
print(f"Mean along columns (axis=0): {data_2d.mean(axis=0)}")

# Max along rows (axis=1)
print(f"Max along rows (axis=1): {data_2d.max(axis=1)}")


2D Data:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Total Sum: 45
Sum along columns (axis=0): [12 15 18]
Sum along rows (axis=1): [ 6 15 24]
Mean along columns (axis=0): [4. 5. 6.]
Max along rows (axis=1): [3 6 9]


### 6. Broadcasting

Broadcasting is a mechanism that allows NumPy to work with arrays of different shapes when performing arithmetic operations. It's a very powerful feature that avoids unnecessary memory duplication.

In [ ]:
# Exercise 6.1: Scalar-array operations

array = np.array([1, 2, 3])
scalar = 5

# Add scalar to each element of the array
print(f"Array: {array}")
print(f"Scalar: {scalar}")
print(f"Result of array + scalar: {array + scalar}")

# Exercise 6.2: Array-array operations with different shapes

a = np.array([[1, 2, 3], [4, 5, 6]]) # Shape (2, 3)
b = np.array([10, 20, 30])         # Shape (3,)

print(f"\nArray a (shape {a.shape}):\n{a}")
print(f"Array b (shape {b.shape}): {b}")

# Add b to each row of a
# NumPy extends b to match the rows of a
print(f"Result of a + b:\n{a + b}")

# Exercise 6.3: More complex broadcasting example

M = np.ones((3, 3)) # Shape (3, 3)
v = np.arange(3)    # Shape (3,)

print(f"\nMatrix M (shape {M.shape}):\n{M}")
print(f"Vector v (shape {v.shape}): {v}")

# Add vector v to each row of matrix M
print(f"Result of M + v:\n{M + v}")

# Add v reshaped to (3,1) (column vector) to each column of M
v_reshaped = v[:, np.newaxis] # or v.reshape(3, 1)
print(f"\nVector v reshaped to (3,1) (shape {v_reshaped.shape}):\n{v_reshaped}")
print(f"Result of M + v_reshaped:\n{M + v_reshaped}")


Array: [1 2 3]
Scalar: 5
Result of array + scalar: [6 7 8]

Array a (shape (2, 3)):
[[1 2 3]
 [4 5 6]]
Array b (shape (3,)): [10 20 30]
Result of a + b:
[[11 22 33]
 [14 25 36]]

Matrix M (shape (3, 3)):
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Vector v (shape (3,)): [0 1 2]
Result of M + v:
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]

Vector v reshaped to (3,1) (shape (3, 1)):
[[0]
 [1]
 [2]]
Result of M + v_reshaped:
[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


### 7. Linear Algebra Operations

NumPy provides a highly optimized `np.linalg` module for performing linear algebra operations, which are the backbone of many machine learning algorithms (e.g., neural networks, PCA, SVD).

#### `np.dot()`: Dot product of two arrays (can be scalar product, vector dot product, or matrix multiplication).
#### `@` operator:  (Python 3.5+) Convenient syntax for matrix multiplication.
#### `np.matmul()`: Matrix product of two arrays.
#### `np.linalg.inv()`: Computes the (multiplicative) inverse of a matrix.
#### `np.linalg.det()`: Computes the determinant of an array.

In [ ]:
# Exercise 7.1: Vector dot product
v1 = np.array([1, 2])
v2 = np.array([3, 4])
print(f"Vector v1: {v1}")
print(f"Vector v2: {v2}")
print(f"Dot product of v1 and v2: {np.dot(v1, v2)}")

# Exercise 7.2: Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(f"\nMatrix A:\n{A}")
print(f"Matrix B:\n{B}")

# Using np.dot()
print(f"Matrix multiplication (np.dot(A, B)):\n{np.dot(A, B)}")

# Using @ operator (preferred for matrix multiplication in Python)
print(f"Matrix multiplication (A @ B):\n{A @ B}")

# Using np.matmul()
print(f"Matrix multiplication (np.matmul(A, B)):\n{np.matmul(A, B)}")

# Exercise 7.3: Inverse and Determinant of a matrix
C = np.array([[1, 2], [3, 4]])
print(f"\nMatrix C:\n{C}")

determinant_C = np.linalg.det(C)
inverse_C = np.linalg.inv(C)

print(f"Determinant of C: {determinant_C:.2f}")
print(f"Inverse of C:\n{inverse_C}")

# Verify C @ C_inv should be identity matrix
identity_check = C @ inverse_C
print(f"C @ Inverse of C (should be identity):\n{identity_check}")


Vector v1: [1 2]
Vector v2: [3 4]
Dot product of v1 and v2: 11

Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]
Matrix multiplication (np.dot(A, B)):
[[19 22]
 [43 50]]
Matrix multiplication (A @ B):
[[19 22]
 [43 50]]
Matrix multiplication (np.matmul(A, B)):
[[19 22]
 [43 50]]

Matrix C:
[[1 2]
 [3 4]]
Determinant of C: -2.00
Inverse of C:
[[-2.   1. ]
 [ 1.5 -0.5]]
C @ Inverse of C (should be identity):
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


### 8. Random Number Generation

The `np.random` module is extensively used in machine learning for tasks like initializing model weights, shuffling data, generating random samples for training/testing, and simulating data. It's important to set a seed for reproducibility.

#### `np.random.seed()`: Sets the seed for NumPy's global random number generator.
#### `np.random.rand()`: Generates random numbers from a uniform distribution over `[0, 1)`.
#### `np.random.randn()`: Generates random numbers from the standard normal distribution (mean 0, variance 1).
#### `np.random.randint()`: Generates random integers.
#### `np.random.choice()`: Generates a random sample from a given 1-D array.
#### `np.random.shuffle()`: Shuffles an array in place.

In [ ]:
# Exercise 8.1: Generate random numbers

# Set a seed for reproducibility
np.random.seed(42)

# Generate a 3x3 array of random numbers between 0 and 1 (uniform distribution)
uniform_random = np.random.rand(3, 3)
print(f"3x3 array from uniform distribution [0, 1):\n{uniform_random}")

# Generate a 2x4 array of random numbers from a standard normal distribution
normal_random = np.random.randn(2, 4)
print(f"\n2x4 array from standard normal distribution:\n{normal_random}")

# Generate 5 random integers between 0 (inclusive) and 10 (exclusive)
random_integers = np.random.randint(0, 10, 5)
print(f"\n5 random integers between 0 and 9: {random_integers}")

# Exercise 8.2: Random choice and shuffling

data = np.array(['apple', 'banana', 'cherry', 'date', 'elderberry'])
print(f"\nOriginal data: {data}")

# Randomly choose 3 elements from the data
chosen_elements = np.random.choice(data, 3, replace=False)
print(f"Randomly chosen 3 elements (without replacement): {chosen_elements}")

# Shuffle the data in place
np.random.shuffle(data)
print(f"Shuffled data (in-place): {data}")


3x3 array from uniform distribution [0, 1):
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]

2x4 array from standard normal distribution:
[[-0.58087813 -0.52516981 -0.57138017 -0.92408284]
 [-2.61254901  0.95036968  0.81644508 -1.523876  ]]

5 random integers between 0 and 9: [9 2 6 3 8]

Original data: ['apple' 'banana' 'cherry' 'date' 'elderberry']
Randomly chosen 3 elements (without replacement): ['banana' 'date' 'elderberry']
Shuffled data (in-place): ['date' 'banana' 'cherry' 'apple' 'elderberry']
